export const publicRoutes = {
  home: '/',
  wineries: '/cantine',
  wineryDetail: (slug: string) => `/cantine/${slug}`,
  events: '/eventi',
  eventDetail: (slug: string) => `/eventi/${slug}`,
  news: '/news',
  newsDetail: (slug: string) => `/news/${slug}`,
  map: '/mappa',
  info: '/informazioni',
  sponsors: '/sponsor',
  gastronomy: '/gastronomia',
  game: '/gioca',
  privacy: '/privacy',
  menu: '/menu',
}

export const adminRoutes = {
  dashboard: '/admin',
  login: '/admin/login',
  wineries: '/admin/cantine',
  newWinery: '/admin/cantine/nuova',
  editWinery: (id: string) => `/admin/cantine/${id}`,
  events: '/admin/eventi',
  newEvent: '/admin/eventi/nuovo',
  editEvent: (id: string) => `/admin/eventi/${id}`,
  news: '/admin/news',
  newNews: '/admin/news/nuova',
  editNews: (id: string) => `/admin/news/${id}`,
  map: '/admin/mappa',
  sponsors: '/admin/sponsor',
  info: '/admin/informazioni',
  game: '/admin/gioco',
  gastronomy: '/admin/gastronomia',
  settings: '/admin/impostazioni',
}
